<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut</name>
   <tag></tag>
   <elementGuidId>1fcef0f7-c89f-4419-9114-3f439592ce0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnLoginEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnLoginEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>474b7984-5140-40cb-a11d-96f77530c09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLoginEmail</value>
      <webElementGuid>a77b09d2-fca5-479e-8b2d-2757cfe23217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-login btn-long remove-margin</value>
      <webElementGuid>6cd1e4ff-317c-4f22-89b4-b28daae13799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>56c80da2-d2fa-4101-9b9e-9e555bd7930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLoginEmail&quot;)</value>
      <webElementGuid>30b89729-dc51-4205-a02e-fa929144aeee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnLoginEmail']</value>
      <webElementGuid>31f68f33-0738-4de6-a0af-2cf2a940dbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-email']/form/div[3]/button</value>
      <webElementGuid>98587d4b-a0e6-4425-b0e0-6c95ea4b9262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Smartlink'])[2]/following::button[1]</value>
      <webElementGuid>d6f42463-9875-4fd1-8453-fe4340dbe327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda sedang offline'])[1]/preceding::button[1]</value>
      <webElementGuid>8e2ca53d-caeb-44c5-8333-9f1f1e6822ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>26d41aeb-bf9d-4198-b5fe-9e290d7587fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnLoginEmail' and (text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>8bbabd03-625e-42ed-97f6-0a664cacda39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
