<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-2</name>
   <tag></tag>
   <elementGuidId>13342c4e-45bf-4bba-8574-4a1cbd36e82b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24c29b2a-5f83-4bfb-8a5e-22dca7656c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c8c24f07-c58d-43b1-9f65-8fdc5f692749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2</value>
      <webElementGuid>68324860-1015-42e0-8410-67b761aa6b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email@email.com</value>
      <webElementGuid>b8f988c2-3052-45f1-819e-d4bdf0fcc74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ac7457a-0bfc-47b5-9791-035f17e4fc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2&quot;)</value>
      <webElementGuid>1ea64224-8601-40da-aba2-37c5e71c07ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-2']</value>
      <webElementGuid>05a97c7a-76d7-4602-9fa2-cd764233d236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-email']/form/div/div[2]/div/input</value>
      <webElementGuid>0d60aad9-d6cd-4a4f-90c6-ce3c078108bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>671eca4b-14bb-4085-bfc4-517ea9b6fa12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'input-2' and @placeholder = 'email@email.com']</value>
      <webElementGuid>cff8c3e6-9cf2-4875-baae-5fc1f7b99e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
