<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lewati</name>
   <tag></tag>
   <elementGuidId>c271e312-216b-43d7-8fe4-9460844c0420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.skip-incontext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view-screen']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90ea9a7b-8395-4bd6-addc-54b4637fc529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-incontext</value>
      <webElementGuid>6a9aa2b1-4a2c-4584-90e1-d6ee7ce94272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lewati</value>
      <webElementGuid>ae09b1e3-2eb7-44e7-ac0e-8050090659d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-screen&quot;)/div[@class=&quot;vh-100&quot;]/div[@class=&quot;vh-100 data_dashboard&quot;]/span[@class=&quot;skip-incontext&quot;]</value>
      <webElementGuid>ad900640-acc8-4607-9e2a-cef9f28d11ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view-screen']/div/div/span</value>
      <webElementGuid>c0e75573-36ec-4d9c-b60e-49ef88f0783a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smartlink'])[1]/preceding::span[1]</value>
      <webElementGuid>31a89846-e0bc-448a-a289-14564aa90903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. ADA IDE LANGSUNG JALAN'])[1]/preceding::span[1]</value>
      <webElementGuid>54053c1f-1fce-4410-99ad-91e79afecc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lewati']/parent::*</value>
      <webElementGuid>9118c736-9c80-4399-b1c7-8cba6c10a583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>f4eeb686-e912-4a29-9b41-3474b9228e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lewati' or . = 'Lewati')]</value>
      <webElementGuid>22f13690-c1bc-41ae-98fa-0191f6a3a5cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
